name: simra

services:
    spring:
        container_name: spring-backend
        build: .  # Requires: ./gradlew build -x test    Build: docker compose build spring
        image: codinggandalf/simra-backend:latest
        # platform: linux/arm64
        env_file:
            - .env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 8080:8080
        depends_on:
            postgis:
                condition: service_healthy
            valhalla:
                condition: service_healthy
            redis:
                condition: service_healthy
        volumes:
            - /home/ben/Documents/simra/dataset/simra-test/Rides:/rides
            - /home/ben/Documents/simra/result-viewer-frontend/src/assets/maplibre:/maplibre-output
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8080/api/actuator/health || true"]
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 10s
        networks:
            - simra-network

    valhalla:
        image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
        ports:
            - 25001:8002
        networks:
            - simra-network
        volumes:
            - ./valhalla/custom_files/:/custom_files
            - ./valhalla/gtfs_feeds:/gtfs_feeds
        environment:
            - tile_urls=https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf
            - server_threads=8
            - use_tiles_ignore_pbf=False
            - tileset_name=valhalla_tiles
            - buildTar=True
            - update_existing_config=True
        healthcheck:
            test: curl --fail -s http://localhost:8002/status || exit 1
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 10s

    redis:
        image: redis:bookworm
        ports:
            - 25002:6379
        volumes:
            - redis-data:/data
        env_file:
            - .env
        networks:
            - simra-network
        healthcheck:
            test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 10s

    init-postgis:
        container_name: init-postgis
        image: ubuntu:24.04
        restart: "no"
        depends_on:
            postgis:
                condition: service_healthy
        command:
          [
              "sh",
              "-c",
              "apt-get update && apt-get install -y osm2pgsql postgresql-client && 
               export PGPASSWORD=${POSTGRES_PASSWORD} && 
               osm2pgsql -d ${POSTGRES_DB} -U ${POSTGRES_USER} -H postgis -C 4096 --number-processes=4 --slim --hstore /tmp/${OSM_MAP_SOURCE}"
          ]
        volumes:
            - ./postgis/data/${OSM_MAP_SOURCE}:/tmp/${OSM_MAP_SOURCE}
        env_file:
            - .env
        networks:
            - simra-network

    postgis:
        container_name: postgis
        image: postgis/postgis:16-3.4 # codinggandalf/postgis:arm64 # official or shell script, database has to initialize osm postgis
        init: true
        shm_size: 4gb
        env_file:
            - .env
        ports:
            - 25432:5432
        volumes:
            - postgis-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-h", "localhost"]
            interval: 30s
            retries: 3
            start_period: 30s
            timeout: 10s
        networks:
            - simra-network

volumes:
    postgis-data:
    redis-data:

networks:
    simra-network:
