name: simra

services:
    spring:
        container_name: spring-backend
        build: .  # Requires: ./gradlew build -x test    Build: docker compose build spring
        image: codinggandalf/simra-backend:latest
        # platform: linux/arm64
        env_file:
            - .env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 8080:8080
        depends_on:
        #    postgis:
        #        condition: service_healthy
            valhalla:
                condition: service_healthy
            redis:
                condition: service_healthy
        volumes:
            # - /home/test/Documents/simra/dataset/RidesLinks:/rides # would copy data from harddrive to docker
            - /home/test/Documents/simra/result-viewer-frontend/src/assets/maplibre:/maplibre-output
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8080/api/actuator/health || true"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 10s
        networks:
            - postgis-service
            - valhalla-service
            - redis-service

    valhalla:
        image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
        ports:
            - 25001:8002
        networks:
            - valhalla-service
        volumes:
            - ./valhalla/custom_files/:/custom_files
            - ./valhalla/gtfs_feeds:/gtfs_feeds
        environment:
            - tile_urls=https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf 
               
            - server_threads=8
            - use_tiles_ignore_pbf=False
            - tileset_name=valhalla_tiles
            - buildTar=True
            - update_existing_config=True
        healthcheck:
            test: curl --fail -s http://localhost:8002/status || exit 1
            interval: 20s
            retries: 10
            start_period: 5s
            timeout: 10s

    redis:
        image: redis:bookworm
        ports:
            - 25002:6379
        volumes:
            - redis-data:/data
        env_file:
            - .env
        networks:
            - redis-service
        healthcheck:
            test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s

    init-postgis:
        container_name: init-postgis
        image: codinggandalf/postgis:arm64-init-postgis
        # platform: linux/arm64
        restart: "no"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command:
          [
              "sh",
              "-c",
              "export PGPASSWORD=${POSTGRES_PASSWORD} &&
         osm2pgsql -d ${POSTGRES_DB} -U ${POSTGRES_USER} -H ${POSTGRES_HOST} -C 4096 --number-processes=4 --slim --hstore /tmp/${OSM_MAP_SOURCE}"
          ]
        #depends_on:
        #    postgis:
        #        condition: service_healthy
        volumes:
            - ./postgis/data/${OSM_MAP_SOURCE}:/tmp/${OSM_MAP_SOURCE}
        env_file:
            - .env
        networks:
            - postgis-service

    #postgis:
    #    container_name: postgis
    #    image: codinggandalf/postgis:arm64 # oficial or shelll script, datenbank muss osm postgis initialisieren
        # platform: linux/arm64
    #    shm_size: 4gb
    #    env_file:
    #        - .env
    #    ports:
    #        - 25432:5432
    #    volumes:
    #        - postgis-data:/var/lib/postgresql/data
    #       - ./postgis/10_enable_postgis.sql:/docker-entrypoint-initdb.d/10_enable_postgis.sql
            # If you want to run initialization scripts, uncomment the following line and add your scripts to the postgis folder
            # - ./postgis/10_postgis.sh:/docker-entrypoint-initdb.d/10_postgis.sh
    #    healthcheck:
    #        test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}", "-h", "localhost"]
    #        interval: 10s
    #        retries: 5
    #        start_period: 10s
    #        timeout: 5s
    #    networks:
    #        - postgis-service

volumes:
    postgis-data:
    redis-data:

networks:
    postgis-service:
    valhalla-service:
    redis-service:
